chessgames/urls.py
from django.urls import path

from chessgames import views

app_name = 'chessgames'

urlpatterns = [
    # path('', views.index, name='index'),  # Debugging only
    path('play/', views.play, name='play'),
    path('play/<game_id>', views.play_game_id, name="play_game_id"),
    path('host_game', views.host_game, name="host_game")
]

polls/urls.py
from django.urls import path

from . import views


# Para namespace em "url names"
app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index')
]

webxadrez/urls.py
from django.shortcuts import redirect

"""webxadrez URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

def index(request):
    return redirect('chessgames:play')

urlpatterns = [
    path('accounts/', include('emailsignup.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('gmailbox/', include('gmailbox.urls')),
    path('chatchannels/', include('chatchannels.urls')),
    path('', index),
    path('chessgames/', include('chessgames.urls'))
]

chessgames/models.py
from chessgames.common.group_msgs import GroupMsgs, group_send
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from chatchannels.models import ChatChannel
from django.dispatch import receiver
from django.db.models.signals import post_delete, pre_delete, post_save


class ChessGame(models.Model):
    history = ArrayField(base_field=models.TextField())
    "Users cannot be deleted as of now. No games will vanish because of this"
    white = models.ForeignKey(User, related_name="white_games", on_delete=models.CASCADE)
    black = models.ForeignKey(
        User, related_name="black_games", blank=True, null=True, on_delete=models.CASCADE)
    start = models.DateTimeField(auto_now_add=True)
    end = models.DateTimeField(blank=True, null=True)
    win = models.CharField(max_length=10, blank=True)
    alive = models.BooleanField(default=False)


class GameSession(models.Model):
    channel = models.ForeignKey(ChatChannel, models.CASCADE)
    chess_game = models.ForeignKey(ChessGame, models.CASCADE)
    ready = models.BooleanField(default=False)


@receiver(post_delete, sender=GameSession, dispatch_uid="delete_game_session_associates")
def delete_game_session_associates(sender, instance, **kwargs):
    """
    A GameSession owns a channel and a chess_game.
    Delete the session and everything goes away
    """
    instance.channel.delete()
    instance.chess_game.delete()


@receiver(pre_delete, sender=ChessGame, dispatch_uid="warn_open_chessgame_consumers")
def warn_open_chessgame_consumers(sender, instance, **kwargs):
    group_send(instance.id, GroupMsgs.g_model_deleted())


@receiver(post_save, sender=ChessGame, dispatch_uid="chessgame_model_changed")
def chessgame_model_changed(sender, instance, **kwargs):
    group_send(instance.id, GroupMsgs.g_model_changed())

chessgames/views.py
from chessgames.models import ChessGame
from chessgames.common.group_msgs import GroupMsgs, group_send
from chessgames.common.move_timer import run_timer
from chatchannels.views import create_channel
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, Http404, redirect
from chessgames.models import GameSession
from django.http import JsonResponse
from django.conf import settings
from threading import Timer


def __delete_game_session_after_timeout(gamesession_id):
    try:
        session = GameSession.objects.get(id=gamesession_id)
        if session.ready is False:
            session.delete()  # Internal signal listeners will delete game and channel
    except GameSession.DoesNotExist:
        pass

    # from django.db import connection
    # connection.close()


def host_game(request):
    """
    POST with authentication:
        Creates a game session in DB and returns its id.
        The stored game session is maintained for only 60 seconds. At the end of this period,
        if no opponent appeared (i.e. session.ready==False), the record is deleted from DB along
        with its ChessGame and ChatChannel
    """
    if request.method != 'POST':
        return JsonResponse({"game_id": None})

    if not request.user.is_authenticated:
        return JsonResponse({"game_id": None})

    channel = create_channel(admins=[request.user], is_public=True)
    game = ChessGame(history=[], white=request.user)
    channel.save()
    game.save()
    session = GameSession(channel=channel, chess_game=game)
    session.save()

    Timer(60.0, __delete_game_session_after_timeout, args=[session.id]).start()

    return JsonResponse({"game_id": session.id})


@login_required()
def play(request):
    pending_games = []
    for session in GameSession.objects.filter(ready=False).all():
        pending_games.append({
            'session_id': session.id,
            'white': session.chess_game.white.username,
            'black': None,
            'history': []
        })

    running_games = []
    for session in GameSession.objects.filter(ready=True, chess_game__win='').all():
        running_games.append({
            'session_id': session.id,
            'white': session.chess_game.white.username,
            'black': session.chess_game.black.username,
            'history': session.chess_game.history
        })

    return render(request, 'chessgames/list.html', {
        'pending_games': pending_games,
        'running_games': running_games
    })


def play_game_id(request, game_id):
    """
    Under GET:
        For authenticated users, renders play page for game session identified by 'game_id'
        (404 if 'game_id' is not in DB)
    Under POST:
        For an authenticated user, sets him as the opponent in game identified by 'game_id'
        (which had already been opened earlier by another user with POST to 'host_game').
        Disallows same user from hosting and playing as his own opponent.
        Returns id of the GameSession
    """

    # Render page if game exists (ready or not); else 404
    if request.method == "GET":
        if not request.user.is_authenticated:
            return redirect(settings.LOGIN_URL)
        try:
            session = GameSession.objects.get(pk=game_id)
        except GameSession.DoesNotExist:
            raise Http404
        # TODO: Really bad ! Channels has no url reversing mechanism like django does
        return render(request, 'chessgames/play.html', {
            "chessgame_ws_endpoint": "chessgames/play/" + str(session.chess_game.id),
            "chatchannel_ws_endpoint": "chatchannels/connect/" + str(session.channel.id),
            "game_id": game_id
        })

    # Register second player and ready=True
    elif request.method == 'POST':
        try:
            session = GameSession.objects.get(pk=game_id, ready=False)
        except GameSession.DoesNotExist:
            session = None

        if session is None or not request.user.is_authenticated:
            return JsonResponse({"game_id": None})

        if session.chess_game.white.id == request.user.id:
            return JsonResponse({"game_id": None})

        session.ready = True
        channel = session.channel
        channel.admins.add(request.user)
        channel.allowed_participants.add(request.user)
        channel.save()
        game = session.chess_game
        game.black = request.user
        game.alive = True
        game.save()
        session.save()

        # White has a fixed time to move. Else, black (current request.user) wins
        run_timer(game.id, move_count=0, winning_player='black')
        group_send(game.id, GroupMsgs.g_game_start(
            opponent=request.user.username))

        return JsonResponse({"game_id": session.id})

webxadrez/templates/chessgames/list.html
{% extends 'base.html' %}
{% load static %}

{% block style %}

<link rel="stylesheet" href="{% static 'vendor/chessboard.css' %}">


<style>
  .col-with-padding {
    box-sizing: border-box !important;
    padding: 0.5rem !important;
  }

  .game-list-collapsable {
    display: flex;
    flex-wrap: wrap;
    margin-top: 1rem;
    justify-content: space-evenly;
  }

  .chessgame-card {
    width: 14rem;
    margin-top: 1rem;
    /* override foundation */
    flex-grow: 0 !important;
  }

  .chessgame-card ul {
    /* override foundation */
    margin-left: 0;
  }
</style>

{% endblock %}

{% block lead %}

<h1 class="display-4">Play a game</h1>
<p>Click on a pending game to play, or on a running game to watch (or even host your own)</p>

{% endblock  %}

{% block content %}

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-with-padding">
      <button onclick="host_your_own()" id="host_your_own_button" class="btn btn-dark">Host your own</button>
    </div>
    <div class="col-sm-12 col-with-padding">
      <button class="btn btn-outline-dark" type="button" data-toggle="collapse" data-target="#pending_games_container">
        <img class="webchess-openclose"> Pending games
      </button>
      <div class="collapse" id="pending_games_container">
        <div class="game-list-collapsable">
          {% for game in pending_games %}
          <div class="card chessgame-card">
            <div class="card-header">
              <div style="display:flex; justify-content: center;">
                <div id="chessgame_{{game.session_id}}" style="width: 12rem;"></div>
              </div>
            </div>

            <ul class="list-group list-group-flush">
              <li class="list-group-item">Offerer: {{ game.white }}</li>
            </ul>

            <div class="card-body">
              <button onclick="play_game({{game.session_id}})" class="btn btn-secondary btn-block btn-chessgame-play">
                Play
              </button>
            </div>

            <div id="chessgame_{{game.session_id}}_alert_container" class="alert alert-dismissible fade" role="alert">
              <strong id="chessgame_{{game.session_id}}_alert_text"></strong>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          </div>
          {% endfor %}
          {% if not pending_games %}
          <div style="display: flex; justify-content: center">
            <p>No one is offering games.</p>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-with-padding">
      <button class="btn btn-outline-dark" type="button" data-toggle="collapse" data-target="#running_games_container">
        <img class="webchess-openclose"> Running games
      </button>

      <div class="collapse" id="running_games_container">
        <div class="game-list-collapsable">
          {% for game in running_games %}
          <div class="card chessgame-card" style="width: 14rem;">
            <div class="card-header">
              <div style="display:flex; justify-content: center;">
                <div onload="create_board_repr('chessgame_{{game.session_id}}', {{game.history | safe}})"
                     id="chessgame_{{game.session_id}}" style="width: 12rem;"></div>
              </div>
            </div>

            <ul class="list-group list-group-flush">
              <li class="list-group-item">White: {{game.white}}</li>
              <li class="list-group-item">Black: {{game.black}}</li>
            </ul>

            <div class="card-body">
              <a href="{% url 'chessgames:play_game_id' game_id=game.session_id %}" class="btn btn-secondary btn-block">Watch</a>
            </div>
          </div>
          {% endfor %}
          {% if not running_games %}
          <div style="display: flex; justify-content: center;">
            <p>No game is being played.</p>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block script %}

<script src="{% static 'vendor/chessboard.js' %}"></script>
<script src="{% static 'vendor/chess.min.js' %}"></script>

<script>
  $().ready(function () {
    var right_chevron = "{% static 'vendor/open-iconic/png/chevron-right-2x.png'  %}";
    var bottom_chevron = "{% static 'vendor/open-iconic/png/chevron-bottom-2x.png'  %}";

    var openclose_selector = '.webchess-openclose';
    var openclose_imgs = $(openclose_selector);

    openclose_imgs.attr('src', right_chevron);

    openclose_imgs.parent().click(function () {
      if ($(this).children(openclose_selector).attr('src') === right_chevron)
        $(this).children(openclose_selector).attr('src', bottom_chevron);
      else
        $(this).children(openclose_selector).attr('src', right_chevron);
    });

  });

  function InteractionButtons(selector) {
    this.els = $(selector);
    this.disabled = false;
  }
  InteractionButtons.prototype.is_disabled = function () {
    return this.disabled;
  };
  InteractionButtons.prototype.toggle =  function () {
    if (this.is_disabled()) {
      this.els.attr('disabled', null);
      this.disabled = false;
    } else {
      this.els.attr('disabled', true);
      this.disabled = true;
    }
  };

  var play_buttons = new InteractionButtons('.btn-chessgame-play');

  var host_button = new InteractionButtons('#host_your_own_button');

  var alerts = {
    __last_class: null,
    __msg: function (game_id, css_class, msg) {
      var container = $('#chessgame_' + game_id + '_alert_container');
      var text = $('#chessgame_' + game_id + '_alert_text');
      if (this.__last_class) {
        container.removeClass(this.__last_class);
      }
      container.addClass(css_class);
      this.__last_class = css_class;
      container.addClass('show');
      text.text(msg);
    },
    error: function (game_id, error_msg) {
      this.__msg(game_id, 'alert-danger', error_msg);
    },
    info: function (game_id, info_msg) {
      this.__msg(game_id, 'alert-primary', info_msg);
    },
    dismiss: function (game_id) {
      $('#chessgame_' + game_id + '_alert_container').removeClass('show');
    }
  };

  function play_game(game_id) {
    if (play_buttons.is_disabled())
      return;

    play_buttons.toggle();

    $.post("{% url 'chessgames:play_game_id' game_id='__slot__' %}".replace('__slot__', game_id)).done(function (data) {

      play_buttons.toggle();

      if (data.game_id !== game_id) {
        // console.log('fail');
        alerts.error(game_id, 'Something went wrong. Someone may have entered the game before you, or you may have' +
          ' tried to play against yourself');
        return;
      }

      // console.log('done');
      alerts.info(game_id, 'Done ! Redirecting you to play arena...');
      window.location.href = "{% url 'chessgames:play_game_id' game_id='__slot__' %}".replace('__slot__', game_id);

    }).fail(function() {
      play_buttons.toggle();

      alerts.error(game_id, 'The server is down, or underwent an internal error. You can try again.')
    });
  }

  function create_board_repr(container_id, moves) {
    var engine = new Chess();
    for (var move of moves) {
      console.log(move);
      var dict = {};
      dict.from = move.substr(0, 2);
      dict.to = move.substr(2, 2);
      if (move.length === 5) {
        dict.promotion = move[4].toLowerCase();
      }
      engine.move(dict);
    }

    ChessBoard(container_id, {
      position: engine.fen(),
      showNotation: false,
      pieceTheme: "{% static 'vendor/chesspieces/wikipedia/' %}{piece}.png"
    });

  }

  function host_your_own() {
    host_button.toggle();
    $.post("{% url 'chessgames:host_game' %}").done(function(data) {
      if (! data.game_id)
        return;
      window.location.href = "{% url 'chessgames:play_game_id' game_id='__slot__' %}".replace('__slot__', data.game_id);
    }).fail(function () {
      host_button.toggle();
    });
  }
</script>

{% for game in pending_games %}
<script>
  create_board_repr('chessgame_{{game.session_id}}', {{game.history | safe}});
</script>
{% endfor %}

{% for game in running_games %}
<script>
  create_board_repr('chessgame_{{game.session_id}}', {{game.history | safe}});
  console.log('created', {{game.history | safe}});
</script>
{% endfor %}


{% endblock %}